### ISSUE TITLE
Criar estrutura de dados dos pontos

### ISSUE THREAD

**Issue by fojacob** [fojacob/Dynamicity#4]
- criar uma classes com descrição e coordenadas do ponto
- fazer uma lista de objetos dessa classe que possam ser renderizados e editados no mapa
- Adicionar novos objetos a essa lista ao desenhar um ponto no mapa com o leaflet-draw

**Comment by Lucasnakajima** [comment]
me adiciona

**Comment by Lucasnakajima** [comment]
@fojacob pull request:

https://github.com/fojacob/Dynamicity/pull/17

**Comment by Lucasnakajima** [comment]
@fojacob testa ai
